# Generated by Django 4.0.3 on 2022-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account_apies', '0002_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
