# Generated by Django 4.0.3 on 2022-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact_us_apies', '0003_remove_eshopcontactus_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EshopSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='eshop_social_medias/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
