# Generated by Django 4.0.3 on 2022-04-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_about_us_apies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='EshopAboutUs',
        ),
    ]
