# Generated by Django 4.0.3 on 2022-04-06 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EshopProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('active', models.BooleanField(default=True)),
                ('is_exit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EshopProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('active', models.BooleanField(default=True)),
                ('is_exit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EshopProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image/')),
                ('active', models.BooleanField(default=True)),
                ('is_exit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EshopProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='size_image/')),
                ('active', models.BooleanField(default=True)),
                ('is_exit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelatedPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='related_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EshopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('slug', models.SlugField()),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='eshop_products_images/')),
                ('active', models.BooleanField(default=True)),
                ('is_sale_product', models.BooleanField(default=False)),
                ('is_whole_product', models.BooleanField(default=False)),
                ('is_popular_product', models.BooleanField(default=False)),
                ('is_exit', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='eshop_produt_apies.eshopproductbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='eshop_produt_apies.eshopproductcategory')),
                ('color', models.ManyToManyField(related_name='color', to='eshop_produt_apies.eshopproductcolor')),
                ('is_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite', to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(related_name='size', to='eshop_produt_apies.eshopproductsize')),
            ],
        ),
    ]
