# Generated by Django 4.0.3 on 2022-04-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_produt_apies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshopproduct',
            name='is_favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eshopproduct',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='size', to='eshop_produt_apies.eshopproductsize'),
        ),
    ]
