# Generated by Django 4.0.3 on 2022-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_produt_apies', '0004_remove_productrelatedphotos_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eshopproduct',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='eshopproduct',
            name='product_photo',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_related', to='eshop_produt_apies.productrelatedphotos'),
        ),
    ]
