# Generated by Django 4.0.3 on 2022-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_produt_apies', '0005_remove_eshopproduct_product_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eshopproduct',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='productrelatedphotos',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_related', to='eshop_produt_apies.eshopproduct'),
        ),
    ]
