# Generated by Django 4.0.3 on 2022-04-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_produt_apies', '0007_remove_eshopproduct_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshopproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='eshop_produt_apies.eshopproductbrand'),
        ),
        migrations.AlterField(
            model_name='eshopproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='eshop_produt_apies.eshopproductcategory'),
        ),
    ]
